# Generated by Django 5.2.3 on 2025-06-16 09:31

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0003_reviews_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='reviews',
            name='mark',
            field=models.PositiveIntegerField(null=True, validators=[django.core.validators.MinValueValidator(1, message='Оценка должна быть не меньше 1.'), django.core.validators.MaxValueValidator(5, message='Оценка должна быть не больше 5.')]),
        ),
    ]
